import { ImportType } from "@/models/ImportSession";

export interface FieldDefinition {
  key: string;
  label: string;
  required: boolean;
  description: string;
  sample: string;
  aliases: string[];
  type: "string" | "number" | "date" | "enum" | "email" | "phone";
  options?: string[];
}

export interface ImportCategoryConfig {
  type: ImportType;
  title: string;
  description: string;
  templateFileName: string;
  fields: FieldDefinition[];
}

export const IMPORT_CONFIGS: Record<ImportType, ImportCategoryConfig> = {
  STUDENTS: {
    type: "STUDENTS",
    title: "Students",
    description: "Import student records, personal profiles, academic placements, and guardian contacts.",
    templateFileName: "student_import_template.xlsx",
    fields: [
      {
        key: "admissionNumber",
        label: "Admission Number",
        required: true,
        description: "Unique school admission number",
        sample: "ADM-2026-001",
        aliases: ["admission no", "admission number", "admission_no", "adm no", "adm_no", "student admission no"],
        type: "string",
      },
      {
        key: "studentId",
        label: "Student ID",
        required: false,
        description: "Custom student identifier (defaults to admission number)",
        sample: "STU-001",
        aliases: ["student id", "student_id", "student code"],
        type: "string",
      },
      {
        key: "firstName",
        label: "First Name",
        required: true,
        description: "Student's first name",
        sample: "Aarav",
        aliases: ["first name", "firstname", "first_name", "student first name"],
        type: "string",
      },
      {
        key: "lastName",
        label: "Last Name",
        required: true,
        description: "Student's last name / surname",
        sample: "Sharma",
        aliases: ["last name", "lastname", "last_name", "surname"],
        type: "string",
      },
      {
        key: "gender",
        label: "Gender",
        required: true,
        description: "Gender: MALE, FEMALE, or OTHER",
        sample: "MALE",
        aliases: ["gender", "sex"],
        type: "enum",
        options: ["MALE", "FEMALE", "OTHER"],
      },
      {
        key: "dateOfBirth",
        label: "Date of Birth",
        required: true,
        description: "Date of birth (YYYY-MM-DD or DD/MM/YYYY)",
        sample: "2015-05-12",
        aliases: ["dob", "date of birth", "date_of_birth", "birth date", "birthdate"],
        type: "date",
      },
      {
        key: "academicYear",
        label: "Academic Year",
        required: true,
        description: "Name of Academic Year configured in ERP",
        sample: "2026-27",
        aliases: ["academic year", "academic_year", "session", "year"],
        type: "string",
      },
      {
        key: "className",
        label: "Class",
        required: true,
        description: "Class name configured in ERP",
        sample: "Class 1",
        aliases: ["class", "class name", "grade", "standard"],
        type: "string",
      },
      {
        key: "sectionName",
        label: "Section",
        required: true,
        description: "Section name within the class",
        sample: "A",
        aliases: ["section", "section name", "division"],
        type: "string",
      },
      {
        key: "rollNumber",
        label: "Roll Number",
        required: false,
        description: "Student roll number in section",
        sample: "101",
        aliases: ["roll no", "roll number", "roll_no", "roll"],
        type: "string",
      },
      {
        key: "email",
        label: "Student Email",
        required: false,
        description: "Student's email address (must be unique if provided)",
        sample: "aarav.sharma@example.com",
        aliases: ["student email", "email", "email address", "student_email"],
        type: "email",
      },
      {
        key: "phone",
        label: "Student Phone",
        required: false,
        description: "Student's contact phone number",
        sample: "9876543210",
        aliases: ["student phone", "phone", "mobile", "student mobile", "phone number"],
        type: "phone",
      },
      {
        key: "bloodGroup",
        label: "Blood Group",
        required: false,
        description: "Blood group (e.g. O+, A+, B+, AB+)",
        sample: "O+",
        aliases: ["blood group", "blood_group", "blood"],
        type: "string",
      },
      {
        key: "admissionDate",
        label: "Admission Date",
        required: false,
        description: "Date of admission (defaults to today)",
        sample: "2026-04-01",
        aliases: ["admission date", "joining date", "admission_date"],
        type: "date",
      },
      {
        key: "status",
        label: "Status",
        required: false,
        description: "Status: ACTIVE, INACTIVE, TRANSFERRED, GRADUATED",
        sample: "ACTIVE",
        aliases: ["status", "student status"],
        type: "enum",
        options: ["ACTIVE", "INACTIVE", "TRANSFERRED", "GRADUATED"],
      },
      {
        key: "street",
        label: "Street Address",
        required: false,
        description: "Street address or residential locality",
        sample: "123 Park Avenue",
        aliases: ["street", "address", "residential address", "street address"],
        type: "string",
      },
      {
        key: "city",
        label: "City",
        required: false,
        description: "City name",
        sample: "Mumbai",
        aliases: ["city", "town"],
        type: "string",
      },
      {
        key: "state",
        label: "State",
        required: false,
        description: "State or Province",
        sample: "Maharashtra",
        aliases: ["state", "province"],
        type: "string",
      },
      {
        key: "postalCode",
        label: "Postal Code",
        required: false,
        description: "Postal code / PIN code",
        sample: "400001",
        aliases: ["postal code", "pin code", "pincode", "zip code", "zip"],
        type: "string",
      },
      // Optional Guardian Info for automatic linking during student import
      {
        key: "parentName",
        label: "Guardian Name",
        required: false,
        description: "Primary parent or guardian full name",
        sample: "Rajesh Sharma",
        aliases: ["parent name", "guardian name", "father name", "mother name", "parent_name"],
        type: "string",
      },
      {
        key: "parentEmail",
        label: "Guardian Email",
        required: false,
        description: "Parent / guardian email for notifications and account",
        sample: "rajesh.sharma@example.com",
        aliases: ["parent email", "guardian email", "father email", "parent_email"],
        type: "email",
      },
      {
        key: "parentPhone",
        label: "Guardian Phone",
        required: false,
        description: "Parent / guardian primary contact number",
        sample: "9876543211",
        aliases: ["parent phone", "guardian phone", "parent mobile", "parent_phone"],
        type: "phone",
      },
      {
        key: "parentRelationship",
        label: "Guardian Relationship",
        required: false,
        description: "Relationship: FATHER, MOTHER, GUARDIAN, OTHER",
        sample: "FATHER",
        aliases: ["relationship", "parent relationship", "guardian relationship"],
        type: "enum",
        options: ["FATHER", "MOTHER", "GUARDIAN", "OTHER"],
      },
    ],
  },

  PARENTS: {
    type: "PARENTS",
    title: "Parents & Guardians",
    description: "Import parent/guardian directory and link them to existing enrolled students.",
    templateFileName: "parent_import_template.xlsx",
    fields: [
      {
        key: "firstName",
        label: "First Name",
        required: true,
        description: "Parent's first name",
        sample: "Rajesh",
        aliases: ["first name", "firstname", "first_name", "parent first name"],
        type: "string",
      },
      {
        key: "lastName",
        label: "Last Name",
        required: true,
        description: "Parent's last name / surname",
        sample: "Sharma",
        aliases: ["last name", "lastname", "last_name", "surname"],
        type: "string",
      },
      {
        key: "email",
        label: "Email",
        required: true,
        description: "Parent's unique email address",
        sample: "rajesh.sharma@example.com",
        aliases: ["email", "email address", "parent email", "parent_email"],
        type: "email",
      },
      {
        key: "phone",
        label: "Phone Number",
        required: true,
        description: "Primary phone number",
        sample: "9876543210",
        aliases: ["phone", "mobile", "phone number", "mobile number", "contact number"],
        type: "phone",
      },
      {
        key: "relationship",
        label: "Relationship",
        required: true,
        description: "Relationship: FATHER, MOTHER, GUARDIAN, OTHER",
        sample: "FATHER",
        aliases: ["relationship", "relation", "guardian type"],
        type: "enum",
        options: ["FATHER", "MOTHER", "GUARDIAN", "OTHER"],
      },
      {
        key: "studentAdmissionNumber",
        label: "Student Admission No(s)",
        required: false,
        description: "Linked student admission number (multiple can be comma-separated)",
        sample: "ADM-2026-001, ADM-2026-002",
        aliases: [
          "student admission number",
          "student admission no",
          "admission no",
          "child admission no",
          "student_admission_number",
          "admission_number",
        ],
        type: "string",
      },
      {
        key: "occupation",
        label: "Occupation",
        required: false,
        description: "Parent profession / occupation",
        sample: "Software Engineer",
        aliases: ["occupation", "profession", "job"],
        type: "string",
      },
      {
        key: "street",
        label: "Street Address",
        required: false,
        description: "Residential address",
        sample: "123 Park Avenue",
        aliases: ["street", "address", "residential address"],
        type: "string",
      },
      {
        key: "city",
        label: "City",
        required: false,
        description: "City name",
        sample: "Mumbai",
        aliases: ["city", "town"],
        type: "string",
      },
      {
        key: "state",
        label: "State",
        required: false,
        description: "State or Province",
        sample: "Maharashtra",
        aliases: ["state", "province"],
        type: "string",
      },
      {
        key: "postalCode",
        label: "Postal Code",
        required: false,
        description: "Postal code / PIN code",
        sample: "400001",
        aliases: ["postal code", "pin code", "pincode", "zip code"],
        type: "string",
      },
      {
        key: "status",
        label: "Status",
        required: false,
        description: "Status: ACTIVE or INACTIVE",
        sample: "ACTIVE",
        aliases: ["status", "parent status"],
        type: "enum",
        options: ["ACTIVE", "INACTIVE"],
      },
    ],
  },

  TEACHERS: {
    type: "TEACHERS",
    title: "Teachers & Staff",
    description: "Import faculty profiles, departmental details, and qualifications.",
    templateFileName: "teacher_import_template.xlsx",
    fields: [
      {
        key: "teacherId",
        label: "Teacher ID",
        required: true,
        description: "Unique institutional teacher identifier",
        sample: "TCH-001",
        aliases: ["teacher id", "teacher_id", "teacher code", "staff id", "employee code"],
        type: "string",
      },
      {
        key: "employeeId",
        label: "Employee ID",
        required: false,
        description: "Optional payroll / HR employee ID",
        sample: "EMP-1001",
        aliases: ["employee id", "employee_id", "emp id", "emp_id"],
        type: "string",
      },
      {
        key: "firstName",
        label: "First Name",
        required: true,
        description: "Teacher's first name",
        sample: "Anita",
        aliases: ["first name", "firstname", "first_name"],
        type: "string",
      },
      {
        key: "middleName",
        label: "Middle Name",
        required: false,
        description: "Teacher's middle name",
        sample: "Kumar",
        aliases: ["middle name", "middlename", "middle_name"],
        type: "string",
      },
      {
        key: "lastName",
        label: "Last Name",
        required: true,
        description: "Teacher's last name / surname",
        sample: "Deshmukh",
        aliases: ["last name", "lastname", "last_name", "surname"],
        type: "string",
      },
      {
        key: "gender",
        label: "Gender",
        required: true,
        description: "Gender: MALE, FEMALE, or OTHER",
        sample: "FEMALE",
        aliases: ["gender", "sex"],
        type: "enum",
        options: ["MALE", "FEMALE", "OTHER"],
      },
      {
        key: "email",
        label: "Email",
        required: false,
        description: "Official or personal email address",
        sample: "anita.deshmukh@school.edu",
        aliases: ["email", "email address", "teacher email", "teacher_email"],
        type: "email",
      },
      {
        key: "phone",
        label: "Phone Number",
        required: false,
        description: "Primary contact number",
        sample: "9876543220",
        aliases: ["phone", "mobile", "phone number", "contact number"],
        type: "phone",
      },
      {
        key: "department",
        label: "Department",
        required: false,
        description: "Academic department (e.g. Science, Mathematics, Languages)",
        sample: "Mathematics",
        aliases: ["department", "dept", "faculty"],
        type: "string",
      },
      {
        key: "designation",
        label: "Designation",
        required: false,
        description: "Title / role (e.g. Senior Teacher, Head of Department, PRT, TGT, PGT)",
        sample: "Senior Teacher",
        aliases: ["designation", "role", "title", "position"],
        type: "string",
      },
      {
        key: "qualification",
        label: "Qualification",
        required: false,
        description: "Educational degrees (e.g. M.Sc. Mathematics, B.Ed.)",
        sample: "M.Sc., B.Ed.",
        aliases: ["qualification", "degree", "education", "qualifications"],
        type: "string",
      },
      {
        key: "joiningDate",
        label: "Joining Date",
        required: false,
        description: "Date of joining institution",
        sample: "2024-06-01",
        aliases: ["joining date", "joining_date", "date of joining", "doj"],
        type: "date",
      },
      {
        key: "dateOfBirth",
        label: "Date of Birth",
        required: false,
        description: "Date of birth",
        sample: "1988-08-15",
        aliases: ["dob", "date of birth", "date_of_birth"],
        type: "date",
      },
      {
        key: "status",
        label: "Status",
        required: false,
        description: "Status: ACTIVE or INACTIVE",
        sample: "ACTIVE",
        aliases: ["status", "teacher status"],
        type: "enum",
        options: ["ACTIVE", "INACTIVE"],
      },
      {
        key: "street",
        label: "Street Address",
        required: false,
        description: "Residential address",
        sample: "45 Hill Road",
        aliases: ["street", "address"],
        type: "string",
      },
      {
        key: "city",
        label: "City",
        required: false,
        description: "City name",
        sample: "Mumbai",
        aliases: ["city"],
        type: "string",
      },
      {
        key: "state",
        label: "State",
        required: false,
        description: "State or Province",
        sample: "Maharashtra",
        aliases: ["state"],
        type: "string",
      },
      {
        key: "postalCode",
        label: "Postal Code",
        required: false,
        description: "Postal code / PIN code",
        sample: "400050",
        aliases: ["postal code", "pin code", "pincode"],
        type: "string",
      },
    ],
  },

  CLASSES: {
    type: "CLASSES",
    title: "Classes",
    description: "Import academic classes and grades for a specific academic year.",
    templateFileName: "class_import_template.xlsx",
    fields: [
      {
        key: "academicYear",
        label: "Academic Year",
        required: true,
        description: "Academic year name (e.g. 2026-27)",
        sample: "2026-27",
        aliases: ["academic year", "academic_year", "session", "year"],
        type: "string",
      },
      {
        key: "className",
        label: "Class Name",
        required: true,
        description: "Name of the class (e.g. Class 1, Grade 10, Nursery)",
        sample: "Class 1",
        aliases: ["class name", "class", "grade", "standard", "class_name"],
        type: "string",
      },
      {
        key: "classCode",
        label: "Class Code",
        required: false,
        description: "Optional short code (e.g. CLS-01, G10)",
        sample: "CLS-01",
        aliases: ["class code", "code", "class_code"],
        type: "string",
      },
      {
        key: "displayOrder",
        label: "Display Order",
        required: false,
        description: "Numerical sequence order for sorting (e.g. 1, 2, 3)",
        sample: "1",
        aliases: ["display order", "order", "sequence", "display_order"],
        type: "number",
      },
      {
        key: "status",
        label: "Status",
        required: false,
        description: "Status: ACTIVE or INACTIVE",
        sample: "ACTIVE",
        aliases: ["status", "is active", "active"],
        type: "enum",
        options: ["ACTIVE", "INACTIVE"],
      },
    ],
  },

  SECTIONS: {
    type: "SECTIONS",
    title: "Sections",
    description: "Import section divisions and capacities for classes in an academic year.",
    templateFileName: "section_import_template.xlsx",
    fields: [
      {
        key: "academicYear",
        label: "Academic Year",
        required: true,
        description: "Academic year name (e.g. 2026-27)",
        sample: "2026-27",
        aliases: ["academic year", "academic_year", "session", "year"],
        type: "string",
      },
      {
        key: "className",
        label: "Class Name",
        required: true,
        description: "Existing class name in the academic year",
        sample: "Class 1",
        aliases: ["class name", "class", "grade", "standard", "class_name"],
        type: "string",
      },
      {
        key: "sectionName",
        label: "Section Name",
        required: true,
        description: "Section name (e.g. A, B, Red, Blue)",
        sample: "A",
        aliases: ["section name", "section", "division", "section_name"],
        type: "string",
      },
      {
        key: "sectionCode",
        label: "Section Code",
        required: false,
        description: "Optional short section code (e.g. SEC-A)",
        sample: "SEC-A",
        aliases: ["section code", "code", "section_code"],
        type: "string",
      },
      {
        key: "capacity",
        label: "Capacity",
        required: false,
        description: "Maximum student seating capacity (defaults to 40)",
        sample: "40",
        aliases: ["capacity", "max students", "seat capacity", "size"],
        type: "number",
      },
      {
        key: "status",
        label: "Status",
        required: false,
        description: "Status: ACTIVE or INACTIVE",
        sample: "ACTIVE",
        aliases: ["status", "is active", "active"],
        type: "enum",
        options: ["ACTIVE", "INACTIVE"],
      },
    ],
  },

  FEES: {
    type: "FEES",
    title: "Fee Payments & Receipts",
    description: "Import historical fee payment receipts and transactional records.",
    templateFileName: "fee_payments_import_template.xlsx",
    fields: [
      {
        key: "admissionNumber",
        label: "Student Admission No",
        required: true,
        description: "Admission number of the student",
        sample: "ADM-2026-001",
        aliases: ["admission no", "admission number", "student admission no", "adm no", "admission_no"],
        type: "string",
      },
      {
        key: "academicYear",
        label: "Academic Year",
        required: true,
        description: "Academic year for the fee payment (e.g. 2026-27)",
        sample: "2026-27",
        aliases: ["academic year", "academic_year", "session", "year"],
        type: "string",
      },
      {
        key: "amount",
        label: "Amount Paid",
        required: true,
        description: "Paid amount in INR (positive number)",
        sample: "15000",
        aliases: ["amount", "paid amount", "amount paid", "total amount", "fee amount"],
        type: "number",
      },
      {
        key: "paymentDate",
        label: "Payment Date",
        required: true,
        description: "Date of payment (YYYY-MM-DD or DD/MM/YYYY)",
        sample: "2026-04-10",
        aliases: ["payment date", "date", "paid date", "payment_date"],
        type: "date",
      },
      {
        key: "paymentMethod",
        label: "Payment Method",
        required: true,
        description: "Method: CASH, BANK_TRANSFER, CHEQUE, UPI, OTHER",
        sample: "UPI",
        aliases: ["payment method", "mode", "payment mode", "method", "payment_method"],
        type: "enum",
        options: ["CASH", "BANK_TRANSFER", "CHEQUE", "UPI", "OTHER"],
      },
      {
        key: "receiptNumber",
        label: "Receipt Number",
        required: true,
        description: "Unique receipt number",
        sample: "RCPT-2026-001",
        aliases: ["receipt no", "receipt number", "receipt_no", "voucher no", "bill no"],
        type: "string",
      },
      {
        key: "transactionId",
        label: "Transaction ID / Ref",
        required: false,
        description: "Cheque no, UPI reference, or UTR number",
        sample: "UPI-982374192",
        aliases: ["transaction id", "ref no", "reference number", "utr", "cheque no", "transaction_id"],
        type: "string",
      },
      {
        key: "remarks",
        label: "Remarks",
        required: false,
        description: "Optional notes or fee breakdown notes",
        sample: "Term 1 Tuition Fee Paid",
        aliases: ["remarks", "notes", "description", "comment"],
        type: "string",
      },
    ],
  },
};
