import ExcelJS from "exceljs";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { ReportResult } from "./types";

export class ReportExportService {
  /**
   * Generates a well-formatted Excel (.xlsx) file buffer from structured report data.
   */
  public static async generateExcelBuffer(result: ReportResult): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = "School ERP SaaS";
    workbook.created = new Date();

    const sheetName = result.metadata.title.slice(0, 30).replace(/[:\\/?*[\]]/g, "_");
    const worksheet = workbook.addWorksheet(sheetName || "Report", {
      views: [{ showGridLines: true }],
    });

    // 1. School Header
    const titleRow = worksheet.addRow([result.metadata.schoolName.toUpperCase()]);
    titleRow.font = { name: "Arial", size: 14, bold: true, color: { argb: "FF312E81" } };
    titleRow.alignment = { horizontal: "left" };

    const subTitleRow = worksheet.addRow([result.metadata.title]);
    subTitleRow.font = { name: "Arial", size: 12, bold: true, color: { argb: "FF4F46E5" } };

    // 2. Metadata details
    worksheet.addRow([`Generated On: ${result.metadata.generatedAt}`]);
    if (result.metadata.generatedBy) {
      worksheet.addRow([`Generated By: ${result.metadata.generatedBy}`]);
    }

    // Applied Filters
    const filterEntries = Object.entries(result.metadata.filtersApplied);
    if (filterEntries.length > 0) {
      const filterText = filterEntries.map(([k, v]) => `${k}: ${v}`).join(" | ");
      worksheet.addRow([`Filters: ${filterText}`]);
    }

    worksheet.addRow([]); // Blank spacer row

    // 3. Table Headers
    const headerTitles = result.columns.map((col) => col.header);
    const headerRow = worksheet.addRow(headerTitles);
    headerRow.height = 24;

    headerRow.eachCell((cell) => {
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FF4F46E5" }, // Indigo primary
      };
      cell.font = { name: "Arial", size: 10, bold: true, color: { argb: "FFFFFFFF" } };
      cell.alignment = { vertical: "middle", horizontal: "center" };
      cell.border = {
        top: { style: "thin", color: { argb: "FFE5E7EB" } },
        bottom: { style: "medium", color: { argb: "FF312E81" } },
      };
    });

    // 4. Data Rows
    for (const item of result.rows) {
      const rowValues = result.columns.map((col) => {
        const val = item[col.key];
        return val !== undefined && val !== null ? val : "—";
      });

      const dataRow = worksheet.addRow(rowValues);
      dataRow.height = 20;

      dataRow.eachCell((cell, colNumber) => {
        const colDef = result.columns[colNumber - 1];
        cell.font = { name: "Arial", size: 9 };
        cell.alignment = {
          vertical: "middle",
          horizontal: colDef?.align || "left",
        };
        cell.border = {
          bottom: { style: "thin", color: { argb: "FFF3F4F6" } },
        };

        // Format numeric / currency
        if (colDef?.format === "currency" && typeof cell.value === "number") {
          cell.numFmt = "₹#,##0.00;[Red]₹-#,##0.00";
        } else if (colDef?.format === "percentage" && typeof cell.value === "number") {
          cell.numFmt = '0.0"%"';
        }
      });
    }

    // 5. Summary Section
    if (result.summary && result.summary.length > 0) {
      worksheet.addRow([]);
      const summaryHeader = worksheet.addRow(["REPORT SUMMARY"]);
      summaryHeader.font = { name: "Arial", size: 10, bold: true, color: { argb: "FF374151" } };

      for (const s of result.summary) {
        const sRow = worksheet.addRow([`${s.label}:`, `${s.prefix || ""}${s.value}${s.suffix || ""}`]);
        sRow.font = { name: "Arial", size: 9 };
      }
    }

    // 6. Auto-fit column widths
    worksheet.columns.forEach((col, index) => {
      const colDef = result.columns[index];
      const headerLen = colDef?.header?.length || 10;
      col.width = Math.max(colDef?.width || 12, headerLen + 4);
    });

    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer);
  }

  /**
   * Generates a high-quality PDF buffer with school branding, headers, tables, and page numbers.
   */
  public static async generatePdfBuffer(result: ReportResult): Promise<Buffer> {
    const isWide = result.columns.length > 7;
    const doc = new jsPDF({
      orientation: isWide ? "landscape" : "portrait",
      unit: "pt",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();

    // 1. School Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(49, 46, 129); // Dark Indigo
    doc.text(result.metadata.schoolName.toUpperCase(), 40, 45);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(79, 70, 229);
    doc.text(result.metadata.title, 40, 65);

    // Meta details
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(107, 114, 128); // Slate 500

    let metaY = 82;
    doc.text(`Generated: ${result.metadata.generatedAt}`, 40, metaY);

    const filterEntries = Object.entries(result.metadata.filtersApplied);
    if (filterEntries.length > 0) {
      metaY += 12;
      const filterStr = filterEntries.map(([k, v]) => `${k}: ${v}`).join("  |  ");
      doc.text(`Filters: ${filterStr}`, 40, metaY);
    }

    // 2. Table Data
    const tableHeaders = [result.columns.map((c) => c.header)];
    const tableBody = result.rows.map((row) =>
      result.columns.map((col) => {
        const val = row[col.key];
        if (val === null || val === undefined) return "—";
        if (col.format === "currency" && typeof val === "number") return `₹${val.toLocaleString("en-IN")}`;
        if (col.format === "percentage" && typeof val === "number") return `${val}%`;
        return String(val);
      })
    );

    autoTable(doc, {
      head: tableHeaders,
      body: tableBody,
      startY: metaY + 16,
      margin: { left: 40, right: 40, top: 40, bottom: 40 },
      styles: {
        font: "helvetica",
        fontSize: 8,
        cellPadding: 5,
        overflow: "linebreak",
      },
      headStyles: {
        fillColor: [79, 70, 229], // Indigo 600
        textColor: 255,
        fontStyle: "bold",
        fontSize: 8.5,
        halign: "center",
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251],
      },
      didDrawPage: (data) => {
        // Footer: Page Numbers
        const pageCount = (doc.internal as any).getNumberOfPages();
        doc.setFontSize(8);
        doc.setTextColor(156, 163, 175);
        doc.text(
          `Page ${data.pageNumber} of ${pageCount} — Confidential School Record`,
          pageWidth / 2,
          doc.internal.pageSize.getHeight() - 20,
          { align: "center" }
        );
      },
    });

    const arrayBuffer = doc.output("arraybuffer");
    return Buffer.from(arrayBuffer);
  }

  /**
   * Generates a clean, sanitized filename for download.
   */
  public static getReportFilename(reportType: string, extension: "xlsx" | "pdf"): string {
    const dateStr = new Date().toISOString().slice(0, 10);
    const safeType = reportType.replace(/[^a-zA-Z0-9_-]/g, "-").toLowerCase();
    return `${safeType}-report-${dateStr}.${extension}`;
  }
}
